Dump detail information for modem command
Instead of an AttributeError: 'NoneType' object has no attribute 'group',
raise exception that reflects better.

BUG=chrome-os-partner:18455
TEST=Manually with a DUT that doesn't have a modem and check the raised
exception.

Change-Id: I243a276e506738de2fb7dc65a4235270642308eb
Reviewed-on: https://gerrit.chromium.org/gerrit/50970
Reviewed-by: Vic Yang <victoryang@chromium.org>
Commit-Queue: Chun-Ta Lin <itspeter@google.com>
Tested-by: Chun-Ta Lin <itspeter@google.com>